language: node.js
node_js:
- 0.12
notifications:
- thiagofernando@outlook.com
before_install:
- npm install -g bower
- npm install grunt
- npm install grunt
- npm install grunt
- npm install grunt
- npm install grunt
>> Local Npm module "grunt-contrib-clean" not found. Is it installed?
>> Local Npm module "grunt-contrib-concat" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?
>> Local Npm module "grunt-usemin" not found. Is it installed?
>> Local Npm module "grunt-ng-annotate" not found. Is it installed?
- npm install -g grunt-cli
- npm install -g karma-cli
- npm install -g protractor
- webdriver-manager update
- bower install
before_script:
- grunt
- cd dist
- npm install karma-phantomjs-launcher --save-dev
script:
- karma start config/karma.config.js --single-run --browsers PhantomJs
