language: node.js
node_js:
- 0.12
notifications:
- thiagofernando@outlook.com
before_install:
- npm install -g bower
- npm install grunt-contrib-clean
- npm install grunt-contrib-copy
- npm install grunt-contrib-concat
- npm install grunt-contrib-uglify
- npm install grunt-contrib-cssmin
- npm install grunt-usemin
- npm install grunt-ng-annotate
- npm install -g grunt-cli
- npm install -g karma-cli
- npm install -g protractor
- webdriver-manager update
- bower install
before_script:
- grunt
- cd dist
- npm install karma-phantomjs-launcher --save-dev
script:
- karma start config/karma.config.js --single-run --browsers PhantomJs
